kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: allow-from-gitea-ns  
spec:  
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: gitea
  policyTypes:
    - Ingress
