kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: dspa-edit  
subjects:
  - kind: ServiceAccount
    name: pipeline-runner-dspa    
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: edit