kind: Secret
apiVersion: v1
metadata:
  name: dashboard-dspa-secret
  labels:
    opendatahub.io/dashboard: 'true'
stringData:
  AWS_ACCESS_KEY_ID: minio
  AWS_SECRET_ACCESS_KEY: minio123
type: Opaque
